In [5]:
%load_ext watermark

In [6]:
%watermark -v -a "Ariel" -p numpy,scipy,matplotlib

Author: Ariel

Python implementation: CPython
Python version       : 3.13.5
IPython version      : 9.4.0

numpy     : 2.3.2
scipy     : 1.16.1
matplotlib: 3.10.5



# 4.1: NumPy Basics

In [6]:
import numpy as np

In [5]:
arr = [1., 2., 3.]
arr1d = np.array(arr)
arr1d.dtype

dtype('float64')

In [8]:
arr1d.astype(np.int32)
arr1d.dtype

dtype('float64')

In [11]:
arr1d.ndim
len(arr1d.shape)

1

In [10]:
arr1d.shape

(3,)

# 4.2: NumPy Array Construction and Indexing

In [14]:
np.ones((3, 4), dtype=np.int16)
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# diagonal matrix
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.arange(3,10)
np.arange(5)
np.arange(1.,2., 0.1)
# np.arange(1, 0.1)
#   array([], dtype=float64) not working as expected

array([], dtype=float64)

In [24]:
np.linspace(0,1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 4.3: NumPy Array Math and Universal Functions